#!/usr/bin/env bash

defaultcmd="mtga"

image=panard/mtga:latest
name=mtga_running
cmd=$defaultcmd
cmdargs=""
opts=()
data="mtga-data-$USER"
do_sound=false
do_update=false

local_data="$HOME/.local/share/mtga"

usage() {
    echo "
Usage: $0 [opts] [image]

Options:
    -h, --help          display this message and exit
    --sound             enable sound (requires PulseAudio and Linux)
    --disable-sound     ensure that sound is disabled
    --cmd CMD           initial command (default: $cmd)
    --data-volume VOL   docker volume to store data (default: ${data})
    --reset             reset local data and docker volume
    --name NAME         container name (default: $name)
    --shell             start an interactive shell instead of MTGO
    --winecfg           run winecfg before calling MTGO
    --dry-run           simply print the docker run command
    --no-tz             disable timezone detection
    --debug             enable debug information
    --test              test environment
    --update            update docker image before run
    -e                  docker run option (environment)
    -v                  docker run option (mount volume)
    -u                  docker run option (change user)
"
}

lopts="dry-run,help,winecfg,shell,cmd:,name:"
lopts="${lopts},data-volume:,reset"
lopts="${lopts},sound,disable-sound"
lopts="${lopts},test"
lopts="${lopts},no-tz"
lopts="${lopts},update"
lopts="${lopts},debug"

getopt=getopt
brew_getopt="/usr/local/opt/gnu-getopt/bin/getopt"
if [[ $OSTYPE == darwin* ]] && [ -x $brew_getopt ]; then
    getopt=$brew_getopt
fi

args="$($getopt -n "${0}" -o hv:u:e: --longoptions $lopts -- "${0}" "${@}")"
if [ $? -ne 0 ]; then
    usage
    exit 1
fi
eval set -- $args

do_run=true
do_reset=false
do_test=false

mytz=${TZ:-}
detect_tz=false
if [ -z "${mytz}" ]; then
    detect_tz=true
fi

while [ -n "${1:-}" ]; do
case "${1:-}" in
    --help|-h)  usage && exit 0 ;;
    --data-volume) shift
        data="$1" ;;
    --debug)
        opts+=("-e" "WINEDEBUG=");;
    --dry-run)
        do_run=false ;;
    --winecfg)
        [[ "$cmd" == "mtgo" ]] && cmdargs="${cmdargs} $1";;
    --sound)
        [[ "$cmd" == "mtgo" ]] && cmdargs="${cmdargs} $1"
        image=panard/mtgo:sound
        do_sound=true ;;
    --disable-sound)
        [[ "$cmd" == "mtgo" ]] && cmdargs="${cmdargs} $1" ;;
    --reset)
        do_reset=true ;;
    --shell)
        cmd="bash"
        cmdargs=""
        opts+=("-it") ;;
    --test)
        local_data="$HOME/.local/share/mtgo-test"
        data="${data}-test"
        do_test=true ;;
    --cmd) shift;
        cmd="$1"
        cmdargs=""
        opts+=("-it") ;;
    --no-tz)
        detect_tz=false
        mytz="" ;;
     --name) shift;
        name="$1" ;;
     --update)
        do_update=true ;;
     -e|-v|-u)
         opts+=("$1" "$2");;
     --) shift ; shift
        if [ -n "${1:-}" ]; then
            image=$1
        fi ;;
esac
shift
done

run() {
    echo "${@}"
    if $do_run; then
        "${@}"
    fi
}

_host_uid=$(id -u)
if [[ ${_host_uid} == 0 ]]; then
    echo "Error: you should not run this script as root."
    echo "Instead, consider adding your user to the 'docker' group:"
    echo "    sudo usermod -aG docker \$USER"
    echo "then restarting your session."
    exit 1
fi

if $detect_tz; then
    if [ -f /etc/timezone ]; then
        mytz=$(</etc/timezone)
    elif [ -L /etc/localtime ]; then
        mytz=$(readlink /etc/localtime |cut -d/ -f 5-)
    elif [[ $OSTYPE == linux-gnu ]]; then
        _tz="$(timedatectl 2>/dev/null|grep "Time zone"|cut -d: -f2|cut -d' ' -f 2)"
        if [ -n ${_tz} ] && [[ "${_tz}" != "n/a" ]]; then
            mytz=$_tz
        fi
    fi
fi

if $do_reset; then
    msg="You are about to delete ${local_data}"
    msg="${msg} and wipe docker volume ${data}"
    echo "WARNING: $msg"
    echo "Press Enter to continue, CTRL+C to abort"
    read
    rm -vrf "${local_data}"
    run docker volume rm $data
fi
if $do_update; then
    run docker pull ${image}
fi

docker volume inspect $data >/dev/null 2>&1
if [ $? -ne 0 ]; then
	set -e
	run docker volume create ${data}

	# migration
	old_data=mtgo-data
	set +e
	docker volume inspect ${old_data}>/dev/null 2>&1
	if [ $? -eq 0 ]; then
		set -e
		echo "Migrating from previous configuration..."
		run docker run --rm -v ${data}:/home/wine/.wine/host \
            -v ${old_data}:/data \
            -v ${local_data}:/ldata \
            -i ${image} bash<<EOF
cp -av /data/* /home/wine/.wine/host/
cp -v /ldata/*.reg /home/wine/.wine/host/
chown -R wine: /home/wine/.wine/host/
EOF
        run docker volume rm ${old_data}
	else
		set -e
		run docker run --rm -v ${data}:/home/wine/.wine/host ${image} true
	fi
fi
set -e

if [ ! -d ${local_data} ]; then
    mkdir -p ${local_data}
fi

opts+=("-v" "${data}:/home/wine/.wine/host/")
opts+=("-v" "${data}:/home/wine/.wine/drive_c/Program Files/Wizards of the Coast/")

reset_xhost=false
if [ ${_host_uid} -ne 1000 ]; then
    run xhost +local:1000
    reset_xhost=true
fi
XSOCK="/tmp/.X11-unix"
XAUTH="${local_data}/Xauthority"
> ${XAUTH}
xauth nlist ${DISPLAY} | sed -e 's/^..../ffff/' | xauth -f ${XAUTH} nmerge -
opts+=("-v" "${XSOCK}:${XSOCK}:rw")
opts+=("-v" "${XAUTH}:/home/wine/.Xauthority:ro")
WEBBROWSER=xdg-open

if $do_sound; then
    _host_pulse="/run/user/${_host_uid}/pulse/native"
    if [ ! -S $_host_pulse ]; then
        echo "PulseAudio does not seem active (${_host_pulse} not found)"
        run pulseaudio --start
    fi
    opts+=("-i" "-v" "${_host_pulse}:/run/user/1000/pulse/native")
fi

opts+=("--net=host" "--ipc=host")
if [ -n "${mytz}" ]; then
    opts+=("-e" "TZ=/usr/share/zoneinfo/${mytz}")
fi

if [ -n "${name}" ]; then
    opts+=("--name" "${name}")
fi

docker_mtgo() {
    run docker run --privileged --rm -e DISPLAY \
        "${opts[@]}" ${image} ${cmd} ${cmdargs}

}
watch_openurl() {
    while read line; do
        echo $line
        if [[ "${line:0:8}" == "OPENURL " ]]; then
            url="${line:8}"
            run $WEBBROWSER "${url}"
        fi
    done
}

if [[ "${cmd}" == "mtga" ]]; then
    docker_mtgo 2>&1 | watch_openurl
else
    docker_mtgo
fi

if $reset_xhost; then
    run xhost -local:1000
fi
