#!/bin/bash

defaultcmd="mtgo"

image=panard/mtgo:latest
name=mtgo_running
cmd=$defaultcmd
opts=""

usage() {
    echo "
Usage: $0 [opts] [image]

Options:
    -h, --help          display this message and exit
    --cmd               initial command (default: $cmd)
    --name              container name (default: $name)
    --shell             start an interactive shell instead of MTGO
    --winecfg           run winecfg before calling MTGO
    --dry-run           simply print the docker run command
    -e                  docker run option (environment)
    -v                  docker run option (mount volume)
    -u                  docker run option (change user)
"
}

args="$(getopt -n "${0}" -o hv:u:e: --longoptions dry-run,help,winecfg,shell,cmd:,name: -- "${0}" "${@}")"
if [ $? -ne 0 ]; then
    usage
    exit 1
fi
eval set -- $args

do_run=true

while [ -n "${1:-}" ]; do
case "${1:-}" in
    --help|-h)  usage && exit 0 ;;
    --dry-run)
        do_run=false ;;
    --winecfg)
        cmd="${defaultcmd} $1" ;;
    --shell)
        cmd="bash" ;;
    --cmd) shift;
        cmd="$1" ;;
     --name) shift;
        name="$1" ;;
     -e|-v|-u)
        opts="${opts} $1 $2" ;;
     --) shift ; shift
        if [ -n "${1:-}" ]; then
            image=$1
        fi ;;
esac
shift
done

run() {
    echo "${@}"
    if $do_run; then
        "${@}"
    fi
}

opts="${opts} -v /tmp/.X11-unix:/tmp/.X11-unix:rw"
opts="${opts} -v $HOME/.Xauthority:/home/wine/.Xauthority:ro"
opts="${opts} --net=host --ipc=host"

# TODO: make this more generic
if [ -f /etc/localtime ] && [ -f /etc/timezone ]; then
    opts="${opts} -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro"
fi

if [ -n "${name}" ]; then
    opts="${opts} --name ${name}"
fi

#-v /run/user/`id -u`/pulse/native:/run/user/1000/pulse/native \
#-v /dev/snd:/dev/snd \

run docker run --privileged --rm -it -e DISPLAY \
    ${opts} ${image} ${cmd}

