#!/bin/bash

defaultcmd="./mtgo"

image=panard/mtgo:latest
name=mtgo_running
cmd=$defaultcmd
opts=""

usage() {
    echo "
Usage: $0 [opts] [image]

Options:
    -h, --help          display this message and exit
    --name              container name (default: $name)
    --shell             start an interactive shell instead of MTGO
    --winecfg           run winecfg before calling MTGO
    --cmd               initial command (default: $cmd)
    -v                  docker run option (mount volume)
    -u                  docker run option (change user)
"
}

args="$(getopt -n "${0}" -o hv:u: --longoptions help,winecfg,shell,cmd:,name: -- "${0}" "${@}")"
eval set -- $args

while [ -n "${1:-}" ]; do
case "${1:-}" in
    --help|-h)  usage && exit 0 ;;
    --winecfg)
        cmd="${defaultcmd} $1" ;;
    --shell)
        cmd="bash" ;;
    --cmd) shift;
        cmd="$1" ;;
     --name) shift;
        name="$1" ;;
     -v) shift
        opts="${opts} -v $1" ;;
     -u) shift
        opts="${opts} -u $1" ;;
     --) shift ; shift
        if [ -n "${1:-}" ]; then
            image=$1
        fi ;;
esac
shift
done

run() {
    echo "${@}"
    "${@}"
}

opts="${opts} -v /tmp/.X11-unix:/tmp/.X11-unix:rw"
opts="${opts} -v $HOME/.Xauthority:/home/wine/.Xauthority:ro"
opts="${opts} --net=host --ipc=host"

opts="${opts} -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro"
#opts="${opts} -e QT_X11_NO_MITSHM=1"

if [ -n "${name}" ]; then
    opts="${opts} --name ${name}"
fi

#-v /run/user/`id -u`/pulse/native:/run/user/1000/pulse/native \
#-v /dev/snd:/dev/snd \
#--net=host \

run docker run --privileged --rm -it -e DISPLAY \
    ${opts} ${image} ${cmd}

